name: Build and Run with Docker

on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code from GitHub
        uses: actions/checkout@v4

      - name: Build the Docker container
        run: docker build -t my-cpp-box .

      - name: Run the Docker container
        run: docker run my-cpp-box